### PR TITLE
webhook: Add skip registry verify functionality

### PR DESCRIPTION
**Pull request by mykolakobzar**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?
Adding skipping tls check functionality for self-signed docker registry 

### Why?
When you have a self-signed certificate in your docker registry, you can face this error from the k8s job with consul temples config.
`time="2022-05-20T17:31:04Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="cannot fetch image descriptor: Get \"https://localhost:8443/v2/\": x509: certificate signed by unknown authority" kind=v1/Pod name=test`

### Additional context
None

### Checklist

- [ ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by bonifaido** [comment]
Thank you! Please sign the CLA @mykolakobzar.

**Comment by mykolakobzar** [comment]
> Thank you! Please sign the CLA @mykolakobzar.

Good morning,
Sorry, done.

**Review by bonifaido — APPROVED** [review]
LGTM!

**Comment by bonifaido** [comment]
Please rebase on main to have the CI fixed.

**Comment by mykolakobzar** [comment]
> Please rebase on main to have the CI fixed.

Good morning, done. Thanks!

**Review by bonifaido — APPROVED** [review]
Thank you!

**Pull request merged**
