### PR TITLE
feature: Refactor auth methods handling and implement purgeUnmanagedConfig

### LINKED ISSUE #605: [cli-tool] Removing externalConfig entity doesn't clean up Vault config
Apologies if this is known/desired behavior. I did some digging through existing issues but wasn't able to find anything.

**Is your feature request related to a problem? Please describe.**
It seems that if you remove a `Vault` CR's `externalConfig` entity in-place, the related entity in the Vault instance's config isn't removed, leaving a "dangling" resource that isn't represented as code.

In other words, if I apply a `Vault` CR with this `externalConfig`:
```yaml
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: test
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
```
And the re-apply with same CR with the `externalConfig` block modified as such, with the `test` policy removed:
```yaml
  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
```
...Vault's config will still retain the `test` policy.

**Describe the solution you'd like**
In the interest of keeping application config declarative, it'd be nice if `bank-vaults configure` was (optionally?) able to clean-up `externalConfig` entities that are no longer under its management. 

**Describe alternatives you've considered**
I guess one could remember to manually clean up old config resources in Vault when they're removed from the Vault CR, but that would defeat the purpose of having declarative config.

### PR DESCRIPTION
**Pull request by wazery**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | yes|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #605, mentioned in #1503 
| License         | Apache 2.0

### What's in this PR?

This PR is part of a series of implementing `purgeUnmanagedConfig` which enables for syncing Vault config with bank-vaults' external configs. As well as refactoring the cli-tool's operator_client.

### Why?

More details can be found in this first PR #605 and this issue #1503 

### Additional context

This PR is concerned with the "Auth Methods" refactoring and the implementation of `purgeUnmanagedConfig`.

#### How to configure `purgeUnmanagedConfig`?

If the user wants to remove any unmanaged config (just policies, auth methods at the moment), they just need to add `purgeUnmanagedConfig` under `externalConfig`:

```
externalConfig:
  purgeUnmanagedConfig:
    enabled: true
```

Auth methods purging can be also disabled by excluding it like so:

```
externalConfig:
  purgeUnmanagedConfig:
    enabled: true
    exclude:
      auth: true
```

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

### CODE REVIEW

**Comment by wazery** [comment]
Hi @bonifaido @pbalogh-sa
I would really appreciate your review and feedback

**Comment by bonifaido** [comment]
On it!

**Comment by bonifaido** [comment]
I guess this is something that has been coordinated with @aabouzaid ? :)

**Comment by wazery** [comment]
Yes, we coordinated together.

**Comment by aabouzaid** [comment]
@bonifaido Yeah, we are coordinating together. He liked the idea wanted to join the forces to make it faster :rocket:

**Comment by bonifaido** [comment]
Really great, thank you for both of you!

**Review by bonifaido — APPROVED** [review]

**Comment by bonifaido** [comment]
If we could give a full example CR (even if just commented out) after all of these PRs are merged, that would be great.

**Comment by aabouzaid** [comment]
@bonifaido no worries, when the PRs are done I will take care of the documentation and examples part.

**Pull request merged**
