### PR TITLE
Add an http health endpoint which can be used by Kubernetes as a liveness probe

### PR DESCRIPTION
**Pull request by ccojocar**
cc @bonifaido

### CODE REVIEW

**Comment by ccojocar** [comment]
@bonifaido I think the test failure does not seem to be related to these changes:
```
#!/bin/bash -eo pipefail
bin/licensei check
github.com/Masterminds/sprig: license violation: NOASSERTION
github.com/magiconair/properties: license violation: NOASSERTION
Exited with code 2
```

**Comment by bonifaido** [comment]
Hi @ccojocar, please ignore the CI check, the license issue will be fixed in #172 .

LGTM. Thank you!

**Comment by bonifaido** [comment]
Please rebase on latest master.

**Comment by ccojocar** [comment]
I fixed the formatting and run successfully the `make verify` locally. I don't know why the build does not pick the latest version. Please could you have a look? Thanks

**Comment by bonifaido** [comment]
No problem, it's a CircleCI issue, I have checked locally and it works fine on my machine as well!

**Comment by raoofm** [comment]
@ccojocar Are you planning to share the helm-chart?

**Comment by matyix** [comment]
thx @ccojocar for the contribution.

**Comment by ccojocar** [comment]
The helm chart is available here https://github.com/jenkins-x/helm-charts/tree/master/vault-operator.

**Comment by raoofm** [comment]
@ccojocar @matyix 
There is one here https://github.com/banzaicloud/banzai-charts/tree/master/vault

Is there a need for another one? Or can you add yours to the same and lets improve upon one?

**Comment by bonifaido** [comment]
That is chart is for installing Vault + Bank-Vaults without the Operator involved. I really like the operator chart created by @ccojocar, can we just move it to the banzai-charts repo as `vault-operator`?

**Pull request merged**
