### PR TITLE
fix: Add missing parameters when using auto unseal

### LINKED ISSUE #1787: Bank-vaults 1.18 operator unable to initialize with auto unsealing
**Describe the bug**:

When creating a new Vault with AWS-based auto unsealing, the operator is unable to initialize the Vault due to an API incompatibility.

~This seems to apply to at least v1.11 and v1.12.~ (read comment below)

**Expected behaviour**:

The Vault should initialize without error.

**Steps to reproduce the bug**:

1. Create an AWS KMS key, an S3 bucket and configure access with the necessary policies.
2. Deploy the following Vault

**Additional context**:

There appears to be different requirements for the API `/sys/init` endpoint between versions.

For v1.11.x, the `stored_shares`, `recovery_shares` and `recovery_threshold` options are required[^1]

```json
{"level":"info","msg":"initializing vault...","time":"2023-02-07T12:38:59Z"}
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2023-02-07T12:38:59Z"}
{"level":"info","msg":"initializing vault","time":"2023-02-07T12:38:59Z"}
{"level":"info","msg":"setting key \"vault-test\" in all 1 key/value Services","time":"2023-02-07T12:38:59Z"}
{"level":"fatal","msg":"error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* recovery configuration must specify a positive number of shares","time":"2023-02-07T12:38:59Z"}
```

For v1.12.x, the `secret_shares` and `secret_threshold` options are not applicable to awskms[^2]

```json
{"level":"info","msg":"initializing vault...","time":"2023-02-07T12:41:46Z"}
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2023-02-07T12:41:46Z"}
{"level":"info","msg":"initializing vault","time":"2023-02-07T12:41:46Z"}
{"level":"info","msg":"setting key \"vault-test\" in all 1 key/value Services","time":"2023-02-07T12:41:46Z"}
{"level":"fatal","msg":"error initializing vault: error initializing vault: Error making API request.\n\nURL: PUT https://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* parameters secret_shares,secret_threshold not applicable to seal type awskms","time":"2023-02-07T12:41:47Z"}
```

[^1]: https://developer.hashicorp.com/vault/api-docs/v1.11.x/system/init#parameters
[^2]: https://developer.hashicorp.com/vault/api-docs/v1.12.x/system/init#parameters

**Environment details**:
- Kubernetes v1.24.8
- bank-vaults v1.18.0

vault.yaml:

```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  serviceAccount: "vault"

  # The vault image to use.
  image: vault:1.12.3

  # The number of replica instances.
  size: 2

  # Add Velero fsfreeze sidecar container and supporting hook annotations to Vault Pods:
  # https://velero.io/docs/v1.2.0/hooks/
  veleroEnabled: true

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    aws:
      kmsKeyId: "<kms key id>"
      kmsRegion: "eu-central-1"
      s3Bucket: "<s3 bucket>"
      s3Region: "eu-central-1"
      s3Prefix: "vault-operator/"

  config:
    api_addr: https://vault.production:8200
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    ui: true
    storage:
      dynamodb:
        ha_enabled: "true"
        table: "<dynamodb table>"
        region: "eu-central-1"
    seal:
      awskms:
        region: "eu-central-1"
        kms_key_id: "<kms key id>"

  credentialsConfig:
    env: AWS_SHARED_CREDENTIALS_FILE
    path: /etc/aws/credentials
    secretName: aws-credentials
```

/kind bug

### PR DESCRIPTION
**Pull request by lusu007**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1787 
| License         | Apache 2.0

### What's in this PR?

This PR checks the seal type and uses the according parameters in the init API call. Furthermore, I updated the vault go api.

### Additional context

This PR is the successor of #1795. I had to create a new one because GitHub force-pushed to my fork and automatically closed the PR when syncing the branch. Sorry for the confusion.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do

- [x]  Test it with all unseal methods (tested with shamir)

### CODE REVIEW

**Comment by lusu007** [comment]
Hey @mkroman,

I fixed the issue we talked about in #1795 in this PR. I hope I didn't confuse you too much with the fact that there is now a new PR... 😅

I would be glad if you could test the PR with your configuration again. 😊

**Comment by lusu007** [comment]
After a test in #1787 this PR is ready now!

**Review by akijakya — APPROVED** [review]
Thanks for the contribution!

**Comment by kirilvasilev** [comment]
I believe this will still cause issues with all seal types that support auto-unseal listed [here](https://developer.hashicorp.com/vault/tutorials/auto-unseal) in vault 1.12.0+ as per the code [here](https://github.com/hashicorp/vault/blob/main/http/sys_init.go#L170). These seals support only `recovery_shares`, `recovery_threshold ` and `recovery_pgp_keys`.

**Pull request merged**
