### PR TITLE
Handling kubernetes auth config

### PR DESCRIPTION
**Pull request by gowthamsubbu**
Method to handle configuring Kubernetes auth method through configuration yaml. #46

### CODE REVIEW

**Comment by bonifaido** [comment]
Thanks for the submission @gowthamsubbu!

Could you please add an example (in a commented out form) to the sample YAML config?

**Comment by gowthamsubbu** [comment]
@bonifaido Update the sample YAML config

**Comment by bonifaido** [comment]
@gowthamsubbu could you please fix the build? I think there is a syntax issue.

**Comment by gowthamsubbu** [comment]
@bonifaido Fixed the syntax and spacing issue. Checks have passed. Please review.

**Comment by gowthamsubbu** [comment]
@matyix Thank you ! Shall we look forward to 2.20 with these changes ?

**Comment by bonifaido** [comment]
Hi @gowthamsubbu, I have tagged 0.2.20, the builds are running on DockerHub already, the images should be available soon.

**Pull request merged**
