### PR TITLE
Update to Vault 1.0.0

### PR DESCRIPTION
**Pull request by bonifaido**
Updates the API client used to talk with Vault 1.0.0.

- [x] Vault 0.11.x still works. (not sure, testing)

Fixes: #222 Depends on: https://github.com/hashicorp/vault/pull/5913

### CODE REVIEW

**Comment by ccojocar** [comment]
@bonifaido Any plans to phase out the `configurer` in favour of newly introduced `Cloud Auto Unseal`? 

https://github.com/hashicorp/vault/blob/master/vault/seal

Thanks

**Comment by bonifaido** [comment]
Hi @ccojocar , autoseal is just unsealing, so I guess you mean not the configurer but the `init/unseal` subcommand of bank-vaults. Since the configurer is widely used part and it relies currently on the keys put to persistent places in the format as `bank-vaults init` does we don't plan to retire the `init/unseal` part soon, also we support  more options (and plan to support even more) for init/unseal, a, like Kubernetes secrets for testing purposes, where you don't have a cloud provider underneath. What I can think of right now is that the configurer could configure a Vault instance that wasn't inited/unseald via bank-vaults, but for that first I have to check how the autounseal actually works.

**Comment by ccojocar** [comment]
Thanks @bonifaido for clarifications. Yeah, I mean the init container. It seems that the vault has a similar approach if you check the implementation, but in addition they wrap the key shards.  https://github.com/hashicorp/vault/blob/1a7cd116a77d12af5df6a7cdd61c358a3324fcbb/vault/seal_autoseal.go#L76. 

Looking at the implementation, it seems to me that all key shards are wrapped, then the wrap key is encrypted with the KMS service, and finally the entire encryption material is stored together in the physical storage. 

Wrapping the keys before storing them, it might have a slightly better security since the wrap key does not have the same level of access like the master key shards.

**Comment by bonifaido** [comment]
Hi @ccojocar, I have created a separate issue for this concern of using auto-unseal: https://github.com/banzaicloud/bank-vaults/issues/228

For the original API compatibility issue, I have pushed a fix which uses a Vault client from our branch temporarily, until the upstream issue gets resolved.

**Pull request merged**
