### PR TITLE
use 'reclaim' policy for host-path PVs

### PR DESCRIPTION
**Pull request by benjamink**
While the snippet for setting up a PV at the end of this file is only for example usage/testing it needs to use the `Reclaim` policy instead of `Delete` as `Delete` isn't supported for `hostPath` PVs.  Having this set to `Delete` would cause the contents of the PV to *NOT* be deleted even when the PV was deleted which would cause bringing up subsequent iterations of Vault to fail.

### CODE REVIEW

**Comment by benjamink** [comment]
This should be `Recycle` not `Reclaim` - fixing.

**Comment by bonifaido** [comment]
Thank you @benjamink, could you please sign the CLA?

**Comment by benjamink** [comment]
Looks like there are bigger issues with this than the single line I changed that are preventing me from merging even after signing the CLA.

**Comment by bonifaido** [comment]
Let me rerun the tests.

**Comment by bonifaido** [comment]
Sorry, I have messed up one of the tools used in the acceptance test, now it should be ok.

**Pull request merged**
