### PR TITLE
Add JWT Auth backend support to bank-vaults cli

### PR DESCRIPTION
**Pull request by primeroz**
Add support for JWT Authentication backend. This is mainly a cut and paste and *change* from the kubernetes one

* Allow for custom path mount
* Tested locally with a manually started vault since i could not find an included testing for this
* Not tested with the operator yet while running in-cluster

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @primeroz, looks great! Could you please sign the CLA as well so I can merge the PR?

**Comment by primeroz** [comment]
@bonifaido I signed the CLA, twice actually, but i can't see the badge or the CI step change. Maybe i am doing something wrong

**Comment by bonifaido** [comment]
The GitHub user who made the commits and your user who created the PR differs (I think this causes the issue). Could you rebase the commits to be made by the same user?

**Comment by primeroz** [comment]
@bonifaido I think messed this up i will open a new merge request all from the same user

**Comment by bonifaido** [comment]
No problem @primeroz.

**Pull request closed without merging**
