### PR TITLE
Multidc use specific loadbalancerip

### PR DESCRIPTION
**Pull request by squaricdot**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
| License         | Apache 2.0

### What's in this PR?
Adding type LoadBalancerIP for the vault crd

### Why?
Selecting a specific loadbalancerIP is sometimes necessary. In case of multiple metallb pools and firewall configuration requirements.

### Additional context
Did test the setup. The setting of the loadbalancerIP of worked. I did experience TLS issues following normal documentation. I did got this fixed by adding:

```
  tlsAdditionalHosts:
    - vault-secondary
    - vault-secondary.default
    - vault-secondary.default.svc.cluster.local
    - vault-tertiary
    - vault-tertiary.default
    - vault-tertiary.default.svc.cluster.local
    - 172.21.123.10  # (lb dc2)
    - 172.21.124.10  # (lb dc1)
```

the code automatically added the executing external loadbalancerLB IP of the respective master instance to the SANs accordingly.

the secondary and tertiary node were provided with:

```
    - name: VAULT_RAFT_CACERT
      value: /vault/raft-tls/ca.crt

  existingTlsSecretName: vault-primary-tls

  volumes:
    - name: vault-primary-tls
      secret:
        secretName: vault-primary-tls
    - name: vault-tls
      secret:
        secretName: vault-primary-tls
```

additionally, to get rid of internal TLS issues this setting was added to all instance cr definitions (cr-primary,secondary,tertiary) 
```
    - name: VAULT_CACERT
      value: /vault/tls/ca.crt
```

### Checklist
- [X] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### To Do

### CODE REVIEW

**Comment by squaricdot** [comment]
I don't see how this change is failing a deployment of cr-raft.yaml

**Review by bonifaido — DISMISSED** [review]
LGTM, thanks ! I rerun the test and now it works fine!

Could you please rebase your commits with your GitHub user email address otherwise the CLA won't pass.

**Review by pbalogh-sa — APPROVED** [review]
Thanks!

**Comment by squaricdot** [comment]
@bonifaido Hi i rebased the commits, thanks.

**Pull request merged**
