### PR TITLE
injector: fix embedded template parsing

### LINKED ISSUE #1728: Please provide urlencode (URL encode) functions
**Is your feature request related to a problem? Please describe.**
I want to make a JDBC URL from Vault secrets with the [Banzai Cloud template engine](https://banzaicloud.com/docs/bank-vaults/operator/templating-configuration/).

**Describe the solution you'd like**
I'm trying to do something like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-db-configmap
  annotations:
    # vault.security.banzaicloud.io settings
data:
  jdbc: postgresql://foo.bar.svc:5432/mydb?user=${vault:secret/database/test#username}&password=${vault:secret/database/test#password}
```

However, my password contains some special characters, so the whole JDBC URL is not a safe URL.

I searched the available functions, but didn't see one that can do urlencode.

**Describe alternatives you've considered**
I may have to do some extra post-processing for the unsafe JDBC URL.

### PR DESCRIPTION
**Pull request by bonifaido**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1728
| License         | Apache 2.0

### What's in this PR?

Support embedded templates inside templates as well.

### Why?

Let's take this example into account, where you need to craft a database url from a secret and encode the password, since it contains some special chars:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-db-configmap
  annotations:
    # vault.security.banzaicloud.io settings
data:
  jdbc: postgresql://foo.bar.svc:5432/mydb?user=${vault:secret/data/account#username}&password=${vault:secret/data/account#${.password | urlquery}}
```

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)

### CODE REVIEW

**Review by akijakya — APPROVED** [review]
Tested, works magnificently!

**Review by pbalogh-sa — APPROVED** [review]
Thx @bonifaido

**Comment by johnlinp** [comment]
Hi @bonifaido @akijakya,

Excuse me, is this fix released in the latest version?

**Comment by akijakya** [comment]
> Hi @bonifaido @akijakya,
> 
> Excuse me, is this fix released in the latest version?

Hi! Sorry for the delay, a new version is planned to be released tomorrow!

**Comment by johnlinp** [comment]
Thank you!

**Comment by akijakya** [comment]
@johnlinp, thanks for the patience, the new version 1.17.0 is out now!

**Pull request merged**
