### PR TITLE
Add custom functions for awskms and file

### LINKED ISSUE #945: [Operator] Source bootstrap secrets from sources other than environment variables
**Is your feature request related to a problem? Please describe.**
I'm trying to bootstrap a database dynamic secrets configuration but I don't want to keep the secret in plain text in source control. Instead, I want to be able to store an encrypted string (in my case encrypted with AWS KMS but could be something else) and be able to reference it similarly to how environment variables are sourced [here](https://github.com/banzaicloud/bank-vaults/blob/master/operator/deploy/cr-mysql-ha.yaml#L67).

**Describe the solution you'd like**
I can use something like `${ file "/path/to/file" }` to reference a volume mount that has the secret I injected securely, `${ awskms "SomeKMSEncryptedString" }` so I can keep the manifest in source control, including `"SomeKMSEncryptedString"`, or even maybe something like `${ keybase "username:SomeGPGEncryptedString" }`. Maybe add custom template functions in addition to the Sprig ones [here](https://github.com/banzaicloud/bank-vaults/blob/master/internal/configuration/template.go#L62)? Or maybe set additional fields in [this](https://github.com/banzaicloud/bank-vaults/blob/master/internal/configuration/template.go#L46) `env` struct that can be queried from the template using dot notation?

**Describe alternatives you've considered**
I tried generating the plain-text string in an init container, write it to a volume that is also mounted on the main `vault-configurer` container and read if from there, but the Sprig library doesn't provide access to the file system or to external binaries.

There could be potential workarounds with creating read-write configmaps, or maybe even a webhook that can modify things on the fly but I think those could add significant complexiy.

**Additional context**
Vault 1.3.2
Bank-vaults operator: 0.9.0
Tried on Kubernetes 1.17, but ideally it would also be supported at least on 1.12

### PR DESCRIPTION
**Pull request by patoarvizu**
Signed-off-by: patoarvizu <patoarvizu@gmail.com>

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #945 
| License         | Apache 2.0

### What's in this PR?
Extending the templating functionality by adding custom functions to enable getting strings from other sources like an AWS KMS-encrypted string or a file path.

### Why?
The only function available for templating that comes close to it is `env` which has limited usefulness for the use case.

### Checklist

- [X] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [X] Logging code meets the guideline (TODO)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### To Do

- Update documentation
- Add examples
- Add/update tests
- Maybe add other sources (e.g. PGP, Google Cloud KMS, a REST endpoint, another Vault, etc.)

### CODE REVIEW

**Comment by patoarvizu** [comment]
@bonifaido here it is! 🙂

**Comment by bonifaido** [comment]
First of all, it looks good to me @patoarvizu ! Don't worry about the CircleCI build, it became flappy because we are running low on resources in the requested VM, we have to increase it probably (the GitHub build which does the same still works).

**Comment by patoarvizu** [comment]
Thanks @bonifaido!

I added a couple of examples (`operator/deploy/cr-file.yaml` and `operator/deploy/cr-awskms.yaml`), but where would be the best place to add actual documentation of the feature? More generally, I don't think that the fact that the Sprig library of functions are available to invoke is documented anywhere, so it might be good to add that as well (I can do it as part of this same PR if you would like me to).

Also, are there any other functions that you think might be good to add? I admit that I'm selfishly only adding `file` and `awskms` because those are the ones that fit my specific use case right now, but I'd be happy to look into other functions, or at least open issues to track them and implement them separately.

**Comment by patoarvizu** [comment]
Ah, also: can you suggest other people I should add as reviewers?

**Comment by bonifaido** [comment]
Hi @patoarvizu !

I just added @pbalogh-sa as well to the review.

The general documentation resides at https://github.com/banzaicloud/bank-vaults-docs

I think we should create a page with a link to http://masterminds.github.io/sprig/ and extend it with the new functions you added, and mention that these functions are available basically everywhere (in config as well).

I think Google KMS would be nice as well! (I think these two providers are used mostly) and maybe Azure later on.

Many thanks for the great work here!

**Comment by patoarvizu** [comment]
Thanks!

Should I start the PR to bank-vaults-docs in parallel to this, or wait until this is merged before I start working on the documentation?

**Comment by bonifaido** [comment]
Just fixed the acceptance test run (with a rerun)

**Comment by patoarvizu** [comment]
Hey guys, I almost have something ready to also support Google Cloud KMS. I want to hold off on merging this and ping you again to review those additional changes when they're ready. Does that work for you?

**Comment by patoarvizu** [comment]
I just added a `gcpkms` function and an example for it. I'm going to set this as 'ready for review' and let you guys take a look whenever you have time. I'm going to get a head start on the documentation on bank-vaults-docs but I can address any feedback you may have here before we merge. Thanks!

**Comment by bonifaido** [comment]
Looks great, looking forward to the docs!🚀 Thanks again!

**Pull request merged**
