### PR TITLE
fix: save recovery key to storage

### PR DESCRIPTION
**Pull request by anasinnyk**
We need to store recovery keys when we make `vault operator init autounseal`

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @anasinnyk, I think this fixes https://github.com/banzaicloud/bank-vaults/issues/228?

**Comment by anasinnyk** [comment]
@bonifaido yes

**Comment by primeroz** [comment]
Should we disable the Unseal functionality of the bank-vaults when running with auto-unseal enabled ? 

Also , when in autounseal mode, i think is a requirement that the `secret_shares` and the `threshold_shares` are set to the same ( see [here](https://www.vaultproject.io/api/system/init.html#secret_threshold) ) and the `stored_shares` are set to the same as secret shares ( see [here](https://www.vaultproject.io/api/system/init.html#stored_shares) )

**Comment by bonifaido** [comment]
Yeah, if auto-unseal is enabled (we can detect this in the operator from the config file) we should disable it.

**Comment by bonifaido** [comment]
We can open another issue from that since this bit can work alone I guess.

**Comment by primeroz** [comment]
Yeah let's extend #228 with the rest of the auto-unseal functionalities

I am just building the image now for testing  , i am not sure we check anything specific in CI for the unseal key and ( in this case ) recovery key storage other than checking that vault is unsealed.

**Comment by bonifaido** [comment]
Nothing is checked other than if Vault is unsealed from this point of view.

**Comment by bonifaido** [comment]
Thanks @anasinnyk !

**Comment by primeroz** [comment]
@anasinnyk even if post merge, do you have an example Configuration file to add to the `operator/deploy` directory with autounseal enabled ?

**Comment by anasinnyk** [comment]
```
    vault:
      customSecrets:
      - secretName: "${var.vault_gcp_sa_secret_name}"
        mountPath: /etc/gcp
      config:
        storage:
          gcs:
            bucket: "${google_storage_bucket.vault_storage.id}"
            ha_enabled: "true"
        seal:
          gcpckms:
            project: "${module.project-factory.project_id}"
            region: "${var.gcp_region}"
            key_ring: "${google_kms_key_ring.key_ring.name}"
            crypto_key: "${google_kms_crypto_key.vault_kms_crypto_key.name}"
      unsealer:
        args:
          - "--store-root-token"
          - "--mode"
          - "google-cloud-kms-gcs"
          - "--google-cloud-kms-key-ring"
          - "${google_kms_key_ring.key_ring.name}"
          - "--google-cloud-kms-crypto-key"
          - "${google_kms_crypto_key.vault_kms_crypto_key.name}"
          - "--google-cloud-kms-location"
          - "${var.gcp_region}"
          - "--google-cloud-kms-project"
          - "${module.project-factory.project_id}"
          - "--google-cloud-storage-bucket"
          - "${google_storage_bucket.vault_storage.id}"
```
I hope it was useful for you

**Comment by bonifaido** [comment]
Thanks!

**Pull request merged**
