### PR TITLE
cross account support for aws auth

### PR DESCRIPTION
**Pull request by gowthamsubbu**
Added support for cross-account access under AWS auth config. Ref #139.

### CODE REVIEW

**Comment by bonifaido** [comment]
@gowthamsubbu thanks for the submission, LGTM! Could you please sign the CLA?

**Comment by gowthamsubbu** [comment]
@bonifaido Signed the CLA

**Comment by matyix** [comment]
thx @gowthamsubbu - merged. We will make a release so you can use that.

**Comment by bonifaido** [comment]
@gowthamsubbu latest release with your changes is now available from DockerHub: 
0.2.18

**Comment by gowthamsubbu** [comment]
@matyix Thank you ! @bonifaido Thanks, let me pull and verify the changes.

**Pull request merged**
