### PR TITLE
vault-env: cache secrets to reduce calls and support dynamic credentials

### LINKED ISSUE #620: [vault-secrets-webhook] add batching support to get dynamic credential
**Describe the bug**:
vault-secrets-webhook is making separate vault call and will not give matching username/password combo for dynamic credential

**Expected behaviour**:
able to retrieve and use dynamic credential with vault-secrets-webhook

**Steps to reproduce the bug**:
Run bank-vaults and set up postgres database secret
Follow guild line on running vault-secrets-webhook to read vault secret and inject into k8s pod
Instead of reading from secret engine, have it retrieve dynamic username/password from postgres database engine using something similar to this

> env:
>   - name: INFLUX_HOST
>     value: vault:v1secret/training/influx#host_private 
>   - name: INFLUX_PORT
>     value: "vault:v1secret/training/influx#port"
>   - name: INFLUX_USERNAME
>     value: vault:postgres/creds/influx-read-only-training#username
>   - name: INFLUX_PASSWORD
>     value: vault:postgres/creds/influx-read-only-training#password
>  
> serviceAccount:
>   create: true
>   name: vault-auth  
> 
> podAnnotations:
>   vault.security.banzaicloud.io/vault-addr: "https://35.245.146.137:8200"
>   vault.security.banzaicloud.io/vault-role: "default"
>   vault.security.banzaicloud.io/vault-skip-verify: "true"
>   vault.security.banzaicloud.io/vault-path: "kubernetes-training"
>   prometheus.io/scrape: "true"
>   prometheus.io/port: "7090"

because webhook will make a separate call to vault, the database username/password combo won't match and you won't be able to log into database

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.11.7
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): GKE
- bank-vaults version (e.g. 0.4.17): 0.5.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

### PR DESCRIPTION
**Pull request by bonifaido**
| Q               | A
| --------------- | ---
| Bug fix?        | yes and no (this is rather a not existing feature)
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #620 
| License         | Apache 2.0

### What's in this PR?
Calling Vault only once per path.

### Why?
To reduce API calls and support dynamic credentials (implicitly).

### Checklist

- [ ] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [ ] Logging code meets the guideline (TODO)

### CODE REVIEW

**Comment by tnguyencota** [comment]
thank you for the quick turn around on this

i tested with master tag and still not getting the right username/password combo as i reported in #620.

below are snippet of webhook and my psql connection test.  if i can provide any other info, please let me know


> ➜  vault-tester git:(master) ✗ kdp vswh-vault-secrets-webhook-7d87bcc9b9-8msmv -n vswh
> Name:               vswh-vault-secrets-webhook-7d87bcc9b9-8msmv
> Namespace:          vswh
> Priority:           0
> PriorityClassName:  <none>
> Node:               gke-training-standard-node-pool-b904f-f5fab0e6-hc2x/10.8.47.218
> Start Time:         Wed, 21 Aug 2019 08:18:11 -0400
> Labels:             app=vault-secrets-webhook
>                     pod-template-hash=7d87bcc9b9
>                     release=vswh
> Annotations:        checksum/config: 08bf54c46f315f84c2f819304bf254368dbbd9874857074c30c872f71423db57
> Status:             Running
> IP:                 x.x.x.x
> Controlled By:      ReplicaSet/vswh-vault-secrets-webhook-7d87bcc9b9
> Containers:
>   vault-secrets-webhook:
>     Container ID:   docker://1d6c349e12f9ed52fbe4e1fa7bf66953311fa6a3ea634dae4a92ff8b35ba3ace
>     Image:          banzaicloud/vault-secrets-webhook:master
>     Image ID:       docker-pullable://banzaicloud/vault-secrets-webhook@sha256:a8e75c03a1aa1773836243e1672ae2a00c911968d564b01bc7b7b153d14255ee
>     Port:           8443/TCP
>     Host Port:      0/TCP
>     State:          Running
>       Started:      Wed, 21 Aug 2019 08:18:12 -0400
>     Ready:          True


> ➜  vault-tester-working git:(master) ✗ kdp test-vault-tester-558f9f98fc-2swbr
> Name:               test-vault-tester-558f9f98fc-2swbr
> Namespace:          default
> Priority:           0
> PriorityClassName:  <none>
> Node:               gke-training-standard-node-pool-b904f-146c6920-csvd/10.8.47.220
> Start Time:         Wed, 21 Aug 2019 09:25:50 -0400
> Labels:             app.kubernetes.io/instance=test
>                     app.kubernetes.io/name=vault-tester
>                     pod-template-hash=558f9f98fc
> Annotations:        kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container vault-tester
>                     vault.security.banzaicloud.io/vault-addr: https://x.x.x.x:8200
>                     vault.security.banzaicloud.io/vault-path: kubernetes-training
>                     vault.security.banzaicloud.io/vault-role: default
>                     vault.security.banzaicloud.io/vault-skip-verify: true
> Status:             Running
> IP:                 x.x.x.x
> Controlled By:      ReplicaSet/test-vault-tester-558f9f98fc
> Init Containers:
>   copy-vault-env:
>     Container ID:  docker://a52eb177ebe2ed1c49217b3fa422232dfb714205f5c28047108594101f2c37ae
>     Image:         banzaicloud/vault-env:latest
>     Image ID:      docker-pullable://banzaicloud/vault-env@sha256:05e583f3a83cb76998988d2d5762a412232cc22e12ee9c3c79511f2461c48587
>     Port:          <none>
>     Host Port:     <none>
>     Command:
>       sh
>       -c
>       cp /usr/local/bin/vault-env /vault/
>     State:          Terminated
>       Reason:       Completed
>       Exit Code:    0
>       Started:      Wed, 21 Aug 2019 09:25:51 -0400
>       Finished:     Wed, 21 Aug 2019 09:25:51 -0400
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       cpu:     50m
>       memory:  64Mi
>     Requests:
>       cpu:        50m
>       memory:     64Mi
>     Environment:  <none>
>     Mounts:
>       /vault/ from vault-env (rw)
> Containers:
>   vault-tester:
>     Container ID:  docker://6863bbc066bee3090447ab0baed661c67354325bb93dbb68e1b7c44a933328ac
>     Image:         library/postgres
>     Image ID:      docker-pullable://postgres@sha256:3aadac317c3f97ac93b30663c86c491867f415b60539edb0511033a1c6e30a10
>     Port:          80/TCP
>     Host Port:     0/TCP
>     Command:
>       /vault/vault-env
>     Args:
>       sh
>       -c
>       while [ true ]; do echo db-host: $PGHOST; echo db-user: $PGUSER; echo db-password: $PGPASSWORD; psql -h $PGHOST -U $PGUSER -w influx; echo going to sleep for 20s; sleep 20; done
>     State:          Running
>       Started:      Wed, 21 Aug 2019 09:25:52 -0400
>     Ready:          True
>     Restart Count:  0
>     Requests:
>       cpu:  100m
>     Environment:
>       PGHOST:                        vault:v1secret/training/influx-quality#db_host
>       PGUSER:                        vault:postgres/creds/enrichment-training#username
>       PGPASSWORD:                    vault:postgres/creds/enrichment-training#password
>       VAULT_ADDR:                    https://x.x.x.x:8200
>       VAULT_SKIP_VERIFY:             true
>       VAULT_PATH:                    kubernetes-training
>       VAULT_ROLE:                    default
>       VAULT_IGNORE_MISSING_SECRETS:  false
>       VAULT_ENV_PASSTHROUGH:


> ➜  vault-tester-working git:(master) ✗ kl test-vault-tester-558f9f98fc-2swbr
> 2019/08/21 13:25:52 Received new Vault token
> 2019/08/21 13:25:52 Initial Vault token arrived
> 2019/08/21 13:25:52 Renewed Vault Token
> db-host: x.x.x.x
> db-user: v-kubernet-enrichme-fDXpThccjeJK6Zi0owIq-1566393952
> db-password: A1a-OrqjuudI3aKdGq1g
> psql: FATAL:  password authentication failed for user "v-kubernet-enrichme-fDXpThccjeJK6Zi0owIq-1566393952"
> FATAL:  password authentication failed for user "v-kubernet-enrichme-fDXpThccjeJK6Zi0owIq-1566393952"
> going to sleep for 20s

**Comment by bonifaido** [comment]
I think it still uses the `latest` tag, the fix is in Digest: sha256:3ca3ca37a498f616250bd7712a494146349ee1748aebaa95253fdb1574530fd5

```yaml
Image: banzaicloud/vault-env:latest
Image ID: docker-pullable://banzaicloud/vault-env@sha256:05e583f3a83cb76998988d2d5762a412232cc22e12ee9c3c79511f2461c48587
```

The image version can be configured here:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault-secrets-webhook/values.yaml#L23

**Comment by bonifaido** [comment]
Could you please try that?

**Comment by tnguyencota** [comment]
that's it.  once i changed VAULT_ENV_IMAGE var to use the right tag, it work
sorry for missing that...

**Comment by bonifaido** [comment]
Cool then! 👍

**Pull request merged**
