### PR TITLE
feat(consul-template): add configuration for template injecting for in init containers

### PR DESCRIPTION
**Pull request by kratisto**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no 
| Related tickets | Partially : #1290 (covers only the consul template part) 
| License         | Apache 2.0

### What's in this PR?

The goal is to add the injection of the configuration generated by consul template in the init containers. 
Obviously this is only possible when not in daemon mode.
I had to move the block injecting the consul-template part in order to guarantee the correct execution order of the init containers. That is to say : 
- vault_agent
- consul_template
- user init containers. 

If I hadn't done so, here is the execution order: 
- consul_template
- vault_agent
- user init containers. 

In order to solve this problem, it was easier to move this code than to go through the list and insert it after the vault-agent. 

I chose to add an activation configuration in order not to make the injection automatic. 

### Why?
I have developed an api that uses liquibase. In order to avoid checking the database every time the application container starts, we decided to use an init container for liquibase. So we need to have access to the configuration generated by consul-template in this init container
### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Review by bonifaido — CHANGES_REQUESTED** [review]
Hi @kratisto, there are still some formatting errors, and also could you please sign the CLA?

**Review by bonifaido — APPROVED** [review]
LGTM! We now just need to have the CLA signed ;)

**Comment by kratisto** [comment]
@bonifaido 
Sorry, I thought I had. 

I just signed it.

Are you planning a new version soon?

**Review by pbalogh-sa — APPROVED** [review]

**Comment by bonifaido** [comment]
Thanks for the feature @kratisto !

Release: maybe today, but Monday at the latest.

**Pull request merged**
