### PR TITLE
Add Thought Machine to adopters file

### PR DESCRIPTION
**Pull request by Tatskaari**

### CODE REVIEW

**Review by bonifaido — APPROVED** [review]
Thank you @Tatskaari for adding yourselves!

**Comment by bonifaido** [comment]
Is it okay to merge @Tatskaari ?

**Review by pbalogh-sa — APPROVED** [review]
Thanks @Tatskaari for adding yourselves!

**Comment by Tatskaari** [comment]
> Is it okay to merge @Tatskaari ?

I think so! Sorry for the many commits, Marketing found out... Just corrected Bank-Vault -> Bank-Vaults... surely I can't have gotten any more stylistic things wrong.

**Review by bonifaido — APPROVED** [review]
No problem, thanks!

**Pull request merged**
