### PR TITLE
Add SETFCAP Capabilities to Helm psp template

### PR DESCRIPTION
**Pull request by inesterenko**
Add missing capability to Helm psp template

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | https://github.com/banzaicloud/bank-vaults/pull/1257
| License         | Apache 2.0

### What's in this PR?

According to https://github.com/banzaicloud/bank-vaults/pull/1257 add missing capability to Helm psp template

### Why?

Current Pod Security Policy  does not allow to deploys vault pods

### Additional context

```
Warning  FailedCreate  56s (x3 over 3m40s)    statefulset-controller  create Pod vault-ph-stage-1 in StatefulSet vault-ph-stage failed error: pods "vault-ph-stage-1" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added spec.containers[0].securityContext.capabilities.add: Invalid value: "IPC_LOCK": capability may not be added spec.containers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added spec.volumes[0]: Invalid value: "configMap": configMap volumes are not allowed to be used spec.volumes[1]: Invalid value: "emptyDir": emptyDir volumes are not allowed to be used spec.containers[0].securityContext.capabilities.add: Invalid value: "IPC_LOCK": capability may not be added spec.containers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added]
```

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Review by pbalogh-sa — COMMENTED** [review]
Thanks, @inesterenko . Please update the chart patch version otherwise LGTM.

**Review by bonifaido — DISMISSED** [review]
LGTM, please also sign the CLA :)

**Comment by bonifaido** [comment]
Ah CLA is signed already, than just the chart bump :)

**Comment by inesterenko** [comment]
@bonifaido  Done. Change chart version
`version: 1.13.1 --> version: 1.13.2`

**Pull request merged**
