### PR TITLE
Prometheus metrics for configurator mode 

### PR DESCRIPTION
**Pull request by primeroz**
Add first implementation of prometheus metric about last configuration run

https://github.com/banzaicloud/bank-vaults/issues/362

prometheus code is shared between unseal and configure operation so I added a flag to the prometheus struct to select which metrics to register. 

it exposes 2 gauge , always increasing, metrics 
 * vault_config_successful - 1 for each successfully applied file
 * vault_config_failed - 1 for each failed applied file

ToDo:
* Port 9091 is not set on the statefulset nor the configurator

### CODE REVIEW

**Comment by bonifaido** [comment]
The CI test started to be very flaky, I think this is because of newly introduced code paths, so I will increase some timeouts.

**Comment by pbalogh-sa** [comment]
@primeroz , please set 9091 in deploymentForConfigurer in vault_controller.go

**Comment by primeroz** [comment]
@pbalogh-sa I don't see it set for the statefulset either, i will set it there too

**Comment by pbalogh-sa** [comment]
Looks good @primeroz

**Comment by primeroz** [comment]
Pull Request ready for review, few things i changed in the last commit 

* Added a new label to the _main_ vault service: **global_service**=true 
  This is needed for CoreOS Prometheus Operator servicemonitor to only pick up the main service and avoid duplicate metrics 
* Port 9091 to the Vault Services 
* Vault Configurator Service

**Pull request merged**
