### PR TITLE
Added release namespace to webhook helm templates

### PR DESCRIPTION
**Pull request by wombat**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | none - fixes configured namespace not being used in the templates
| License         | Apache 2.0

### What's in this PR?
We configured a namespace with helm but the namespace was not used at all points within the templates

### Checklist

- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by pbalogh-sa** [comment]
Thanks, @wombat ! Please increment chart version.

**Comment by wombat** [comment]
@pbalogh-com awesome - should I increase it? to 0.5.4?

**Comment by bonifaido** [comment]
That should be fine!

**Comment by wombat** [comment]
@bonifaido done - I was not sure if I should also increase ` tag: 0.5.1` to `  tag: 0.5.4` in the `values.yaml` so I left it but can also update it if necessary

**Pull request merged**
