### PR TITLE
Add ServiceAccount configurability to CRD

### PR DESCRIPTION
**Pull request by bonifaido**
Fixes: https://github.com/banzaicloud/bank-vaults/issues/200

### CODE REVIEW

**Comment by bonifaido** [comment]
@cu12 could you please make sure that the latest image is actually the `"latest"` and send us how your Vault CRD looks like?

**Comment by cu12** [comment]
@bonifaido nevermind, one shall not only bump `bank-vault` version but the operator too ;)

**Comment by bonifaido** [comment]
Happy to help!

**Comment by tiferrei** [comment]
Hi, is this available through the helm chart? Getting the same issues as #200 but with helm installs.

**Pull request merged**
