### PR TITLE
configurer: Finalize config purge feature

### PR DESCRIPTION
**Pull request by aabouzaid**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | #1503, #1513, #1514, #1519, #1520, #1532, #1535
| License         | Apache 2.0

### What's in this PR?
This PR wraps and finalizes the config purge feature.

I've written a bash script and Github Actions workflow that test the config CRUD to make sure we don't introduce any breaking changes.

No new code is expected but could be bug fixes or code tidy up to keep the code consistent across config sections (audit, auth, secrets, etc.)

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

### CODE REVIEW

**Comment by aabouzaid** [comment]
@bonifaido could you please process with PRs no. #1532 and #1535 so I can finalize this feature.

**Comment by aabouzaid** [comment]
@bonifaido The feature has been implemented, tested, and documented. So it's ready to be released :rocket:  

Thanks to @wazery for his great contribution to this big feature by adding `audit`, `auth`, and `startupSecrets` :clap:

**Review by bonifaido — APPROVED** [review]
Extremely cool work, thank you very much!

I have seen there is a new CI test, that is another +1!

**Comment by aabouzaid** [comment]
@bonifaido Thank you :rocket: 
I believe we are ready for the new release :tada:

**Comment by bonifaido** [comment]
Yes, soon, we are waiting for a fix, since 1.15 introduced a breaking change in the secrets webhook, when using with the sidecar, and the fix is in the making already!

**Comment by chrism417** [comment]
This breaks every attempt at updating from 1.14 to 1.15.

**Comment by aabouzaid** [comment]
@chrism417 please open a new issue with all details.

**Comment by chrism417** [comment]
There are several issues already opened and discussed in the slack channel. This is the one I have going from 1.14 to 1.15: https://github.com/banzaicloud/bank-vaults/issues/1638

**Pull request merged**
