### PR TITLE
Geneate the client for Vault resource not VaultList

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by ccojocar** [comment]
@bonifaido It seems some issue with `golint` installation:
```
go get github.com/golang/lint/golint
package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Makefile:75: recipe for target 'install-golint' failed
make: *** [install-golint] Error 1
```

`make verify` works fine locally for me.

**Comment by bonifaido** [comment]
I just rerun the build to see if it is an intermittent issue (it works fine locally).

**Comment by bonifaido** [comment]
I was wrong, there is an issue with `golint` itself: `go get -u github.com/golang/lint/golint` doesn't work (I was having it checked out previously, that is why it worked).

**Comment by bonifaido** [comment]
https://github.com/golang/lint/issues/417

**Comment by bonifaido** [comment]
Thanks @ccojocar , merged, we don't wait for go lint fix for, it worked with the previous golint I have checked locally. :)

**Comment by matyix** [comment]
thx @ccojocar

**Pull request merged**
