### PR TITLE
configurer: Allow to specify options on kv2 writes

### PR DESCRIPTION
**Pull request by avoidik**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/1576
| License         | Apache 2.0

### What's in this PR?

That's my attempt to enable extra CAS options on writes to KVv2 backend, such as

```
    startupSecrets:
      - type: kv
        path: secret/data/info
        data:
          data:
            APP_LOGIN: user
            APP_PASSWORD: password
          options:
            cas: 0
```

### Why?

https://github.com/banzaicloud/bank-vaults/issues/1576

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do

- [x] let's run CI and see how it goes

### CODE REVIEW

**Comment by avoidik** [comment]
while I was trying to implement basic tests I have noticed the following:
- `ServiceAccountIssuerDiscovery` feature-gate can be removed from the kind configuration file, since it's enabled by default after k8s v1.19 (newer version of kind was unable to start with `Failed to set feature gates from initial flags-based config" err="unrecognized feature gate: ServiceAccountIssuerDiscovery`), [ref.](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)
- missing wait step after the `vault-secrets-webhook` deployment in the `acceptance-test.sh` file
- some sample CRs have docker images tagged as `:main` that do not exist

**Comment by avoidik** [comment]
@bonifaido could you please advise, looks like acceptance test were failing on something non-relevant to my change

**Comment by bonifaido** [comment]
The test is sometimes flaky, since the resources are a bit constrained here in GitHub actions, so I kicked it again, will watch for it.

**Comment by bonifaido** [comment]
The build is green now! I will review shortly...

**Comment by bonifaido** [comment]
> * `ServiceAccountIssuerDiscovery` feature-gate can be removed from the kind configuration file, since it's enabled by default after k8s v1.19 (newer version of kind was unable to start with `Failed to set feature gates from initial flags-based config" err="unrecognized feature gate: ServiceAccountIssuerDiscovery`), [ref.](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

Great finding, could you please remove this? I think we are using k8s 1.21, so it should be the default now as you say.

**Comment by avoidik** [comment]
@bonifaido feature-gate was removed, acceptance-test passed

**Review by bonifaido — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
