### PR TITLE
Add `aws-iam` auth method in vault-env

### PR DESCRIPTION
**Pull request by cdgz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?
This PR adds `aws-iam` vault login method, which implements `vault write auth/aws/role/<iam_role> auth_type=iam` from [Vault docs](https://www.vaultproject.io/docs/auth/aws#perform-the-login-operation). Code is based on example implementation in Vault CLI ([1](https://github.com/hashicorp/vault/blob/412db2245e81f1c130d94823994987cb8e9d2595/builtin/credential/aws/cli.go#L51), [2](https://github.com/hashicorp/go-secure-stdlib/blob/5b6393aa5d82ceb91cfdfe9e7a2fefb9bcc03b7b/awsutil/generate_credentials.go#L256-L301)) with credentials being fetched with the help of AWS SDK Go's [`stscreds.WebIdentityRoleProvider`](https://github.com/aws/aws-sdk-go/blob/92b5621bf8338d68f64c79cd094969d289428723/aws/session/credentials_test.go#L818) (available in newer version, hence bump).

### Why?
AWS IAM auth method is available in Vault so should be in bank-vaults.

### Additional context
For the context, I roughly followed [this guide](https://deployment.properties/posts/devsecops/vault-eks-irsa/) on how to ensure AWS IAM authentication works outside bank-vaults infra.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ ] User guide and development docs updated (if needed)
- [ ] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @cdgz, could you please update your commit to match your GitHub user's email address, so the CLA check can pass?

**Comment by cdgz** [comment]
@bonifaido Done. Currently getting empty window in CLA assessment check.

<details>

Screen Shot 2022-01-26 at 14 07 09

</details>

**Comment by bonifaido** [comment]
It takes some time to load now (I don't know the reason) but it will appear after a few seconds (5-15s).

Is the PR ready for review now?

**Comment by cdgz** [comment]
@bonifaido Pushed lint fixes, `make check` passes locally for me

<details>

```
❯ VAULT_TOKEN=$(cat vault-root) make check
bin/golangci-lint run
cd pkg/sdk && ../../bin/golangci-lint run
bin/gotestsum --no-summary=skipped --junitfile build/test_results/integration/results.xml --format short -- -tags=integration ./...
✓  pkg/kv (cached)
✓  internal/injector (cached)
∅  cmd/bank-vaults
∅  cmd/template
∅  cmd/vault-env
∅  cmd/vault-secrets-webhook
∅  internal/configuration
∅  internal/vault
✓  pkg/webhook (cached)
∅  operator/cmd/manager
∅  operator/pkg/apis
∅  operator/pkg/apis/vault/v1alpha1
∅  operator/pkg/client/clientset/versioned
∅  operator/pkg/client/clientset/versioned/fake
∅  operator/pkg/client/clientset/versioned/scheme
∅  operator/pkg/client/clientset/versioned/typed/vault/v1alpha1
∅  operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/fake
∅  operator/pkg/client/informers/externalversions
∅  operator/pkg/client/informers/externalversions/internalinterfaces
∅  operator/pkg/client/informers/externalversions/vault
∅  operator/pkg/client/informers/externalversions/vault/v1alpha1
∅  operator/pkg/client/listers/vault/v1alpha1
∅  operator/pkg/controller
∅  operator/pkg/controller/vault
∅  operator/version
∅  pkg/kv/alibabakms
∅  pkg/kv/alibabaoss
∅  pkg/kv/awskms
∅  pkg/kv/azurekv
∅  pkg/kv/dev
∅  pkg/kv/file
∅  pkg/kv/gckms
∅  pkg/kv/gcs
✓  pkg/kv/hsm (100ms)
∅  pkg/kv/k8s
∅  pkg/kv/multi
∅  pkg/kv/s3
∅  pkg/kv/vault

DONE 27 tests in 1.325s
cd pkg/sdk && ../../bin/gotestsum --no-summary=skipped --junitfile ../../build/test_results/integration/results.xml --format short -- -tags=integration ./...
✓  log (250ms)
✓  vault (264ms)
✓  auth (566ms)
∅  db
✓  tls (1.341s)

DONE 23 tests in 2.088s

```

</details>

**Review by bonifaido — APPROVED** [review]
LGTM! Thank you very much!

**Pull request merged**
