### PR TITLE
Extend the Vault CRD with a configuration for credentials (aka service account)

### PR DESCRIPTION
**Pull request by ccojocar**
- This configuration can be used to mount a dedicated service account with the required roles only in the vault,unsealer and configurator containers.
- Add a script which generates the boilerplate code for Vault CRD
- Regenerate the boilerplate code

### CODE REVIEW

**Comment by bonifaido** [comment]
Hi @ccojocar, by " boilerplate code for Vault CRD" you mean an API client for Vault objects?

**Comment by ccojocar** [comment]
Right, and deep copy

**Comment by ccojocar** [comment]
I tested right now with GKE, and it works well.

**Comment by bonifaido** [comment]
Great! Could you please have look at the build, it has some issues with `VaultList` objects.

**Comment by ccojocar** [comment]
@bonifaido It seems that some of the code generated for the client was not compiling. The build is not green.

**Comment by bonifaido** [comment]
Now the build is fine, I will have a look at this soon. Thank you!!

**Pull request merged**
