### PR TITLE
update Chart version

### PR DESCRIPTION
**Pull request by nullck**
Signed-off-by: Thiago Dias <nullck@gmail.com>

| Q               | A
| --------------- | ---
| License         | Apache 2.0

### What's in this PR?
Just a Chart update

### Checklist
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by bonifaido** [comment]
Currently, the latest version of the webhook is 0.6.3 :)

**Comment by nullck** [comment]
@bonifaido  I forgot to update the Chart version when we merge my latest PR - https://github.com/banzaicloud/bank-vaults/pull/780

**Comment by bonifaido** [comment]
https://github.com/banzaicloud/bank-vaults/pull/780/files#diff-d86e687195b6cb9eb405a31ffd3ca777L5 you didn't! :)

**Comment by nullck** [comment]
you're right, my mistake

**Pull request closed without merging**
